[package]
name = "prettifyjsonstring"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.19"
serde_json = "1.0"
wasm-bindgen = "0.2.80"
web-sys = { version = "0.3.57", features = ["HtmlTextAreaElement"] }
wasm-logger = "0.2.0"
snailquote = "0.3.1"
